# Generated by Django 4.1.1 on 2022-09-24 01:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("Customer_Id", models.AutoField(primary_key=True, serialize=False)),
                ("Customer_Name", models.CharField(max_length=255)),
                ("Customer_Facebook", models.CharField(max_length=255)),
                ("Customer_Phone", models.CharField(max_length=10)),
                ("Customer_ZaloName", models.CharField(max_length=255)),
                ("Customer_Address", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Paymentstatus",
            fields=[
                (
                    "Paymentstatus_Id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("Paymentstatus_Name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("Product_Id", models.AutoField(primary_key=True, serialize=False)),
                ("Product_Name", models.CharField(max_length=255)),
                ("Product_Price", models.BigIntegerField()),
                ("IsActive", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                ("Source_Id", models.AutoField(primary_key=True, serialize=False)),
                ("Source_Name", models.CharField(max_length=255)),
                ("Source_Link", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Workingstatus",
            fields=[
                (
                    "Workingstatus_Id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("Workingstatus_Name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Donhang",
            fields=[
                ("Donhang_Id", models.AutoField(primary_key=True, serialize=False)),
                ("Donhang_Name", models.CharField(max_length=255)),
                ("FlashDesign_Flag", models.IntegerField()),
                (
                    "CreatedDate",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("Deadline", models.DateTimeField()),
                ("Donhang_Require", models.CharField(max_length=1000)),
                ("Donhang_Price_Combo", models.BigIntegerField()),
                ("Donhang_Price_Discount", models.BigIntegerField()),
                ("Donhang_Price_Upsale", models.BigIntegerField()),
                ("Donhang_Price_Payment", models.BigIntegerField()),
                (
                    "Customer_Id",
                    models.ForeignKey(
                        db_column="Customer_Id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Quanlybanhang.customer",
                    ),
                ),
                (
                    "PaymentStatus_Id",
                    models.ForeignKey(
                        db_column="Paymentstatus_Id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Quanlybanhang.paymentstatus",
                    ),
                ),
                (
                    "Product_Id",
                    models.ForeignKey(
                        db_column="Product_Id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Quanlybanhang.product",
                    ),
                ),
                (
                    "WorkingStatus_Id",
                    models.ForeignKey(
                        db_column="Workingstatus_Id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Quanlybanhang.workingstatus",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="customer",
            name="Source_Id",
            field=models.ForeignKey(
                db_column="Source_Id",
                on_delete=django.db.models.deletion.CASCADE,
                to="Quanlybanhang.source",
            ),
        ),
    ]
