# Generated by Django 4.1.1 on 2022-09-24 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Quanlybanhang", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="donhang", name="PaymentStatus_Id",),
    ]
