# Generated by Django 4.1.1 on 2022-09-25 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Quanlybanhang", "0002_remove_donhang_paymentstatus_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="donhang", name="IsDelete", field=models.IntegerField(default=0),
        ),
    ]
