# Generated by Django 4.1.1 on 2022-09-27 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Quanlybanhang", "0003_donhang_isdelete"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="Customer_Address",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="Customer_Phone",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="Customer_ZaloName",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
