# Generated by Django 4.1.1 on 2022-09-27 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Quanlybanhang", "0004_alter_customer_customer_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donhang", name="Deadline", field=models.IntegerField(),
        ),
    ]
