# Generated by Django 4.1.1 on 2022-10-03 10:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Quanlybanhang', '0005_alter_donhang_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='donhang',
            name='CreatedDateOrigin',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
