# Generated by Django 4.1.1 on 2022-10-03 21:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Quanlybanhang', '0006_donhang_createddateorigin'),
    ]

    operations = [
        migrations.AddField(
            model_name='donhang',
            name='LastUpdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 3, 21, 51, 49, 635577)),
        ),
        migrations.AddField(
            model_name='donhang',
            name='Username',
            field=models.ForeignKey(db_column='User', default=4, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donhang',
            name='CreatedDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 3, 21, 51, 49, 635577)),
        ),
        migrations.AlterField(
            model_name='donhang',
            name='CreatedDateOrigin',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 3, 21, 51, 49, 635577)),
        ),
    ]
