# Generated by Django 4.1.1 on 2022-10-04 13:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quanlybanhang', '0007_donhang_lastupdate_donhang_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donhang',
            name='CreatedDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 4, 13, 17, 3, 169858)),
        ),
        migrations.AlterField(
            model_name='donhang',
            name='CreatedDateOrigin',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 4, 13, 17, 3, 169858)),
        ),
        migrations.AlterField(
            model_name='donhang',
            name='LastUpdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 4, 13, 17, 3, 169858)),
        ),
    ]
