# Generated by Django 4.1.1 on 2022-10-07 23:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quanlybanhang', '0009_donhang_image1_donhang_image2_donhang_image3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donhang',
            name='CreatedDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 7, 23, 39, 54, 879442)),
        ),
        migrations.AlterField(
            model_name='donhang',
            name='CreatedDateOrigin',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 7, 23, 39, 54, 879442)),
        ),
        migrations.AlterField(
            model_name='donhang',
            name='Image1',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='donhang',
            name='Image2',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='donhang',
            name='Image3',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='donhang',
            name='Image4',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='donhang',
            name='Image5',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='donhang',
            name='Image6',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='donhang',
            name='LastUpdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 7, 23, 39, 54, 879442)),
        ),
    ]
