# Generated by Django 4.1.1 on 2022-10-14 02:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quanlybanhang', '0011_alter_donhang_createddate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donhang',
            old_name='WorkingStatus_Id',
            new_name='Workingstatus_Id',
        ),
        migrations.AlterField(
            model_name='donhang',
            name='CreatedDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 14, 2, 0, 16, 869906)),
        ),
        migrations.AlterField(
            model_name='donhang',
            name='CreatedDateOrigin',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 14, 2, 0, 16, 869906)),
        ),
        migrations.AlterField(
            model_name='donhang',
            name='LastUpdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 14, 2, 0, 16, 869906)),
        ),
    ]
